### ISSUE TITLE
The newer Cupy AsyncMempool crashes clone_here / copy_from_async

### ISSUE THREAD

**Issue by dialecticDolt** [ut-parla/parla-experimental#127] opened 2023-08-02 18:17 UTC
If we can reproduce this in isolation on the newest version of CuPy, it should be upstreamed as an issue to them.

**Comment by ShreyaTalati** [comment] 2023-11-14 20:34
Do you remember the version of CuPy you observed the error in?
I have CuPy 12.2 (latest version) and I ran this code file having multiple `clone_here

**Comment by ShreyaTalati** [comment] 2023-11-14 20:38
Do you remember the version of CuPy you observed the error in?
I have CuPy 12.2 (latest version) and I ran [this cholesky code file](https://github.com/ut-parla/parla-experimental/blob/main/example/cholesky_gpu_manual.py ) having `clone_here` called multiple times - 
and [sample_sort](https://github.com/ut-parla/parla-experimental/commit/28c39a8f835e6b18effdf454441edffa4f9c9845) with `copy_from_async` called. Both worked fine on my end.

**Comment by ShreyaTalati** [comment] 2023-11-16 19:02
The issue is not present in latest CuPy version. Closing the issue

**Closed by ShreyaTalati** 2023-11-16 19:02 UTC
